apiVersion: apps/v1
kind: Deployment
metadata:
  name: paw-eks-deployment-nginx-dev-sydney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        service: nginx
        app: nginx
    spec:
      containers:
      - image: nginx
        name: paw-eks-deployment-nginx-dev-sydney
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      # nodeSelector:
      #   instance-type: spot
